#!/usr/bin/env bash
# Installs nginx web server and configures redirection

apt-get update
apt-get install -y nginx

# Create custom HTML page with content "Best School"
echo "Best School" > /etc/nginx/html/index.html

# Configure Nginx redirection rule
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://github.com/Osei531;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
service nginx restart

