#!/usr/bin/env bash
# Installs nginx web server and configures custom 404 page

apt-get update
apt-get install -y nginx

# Start Nginx service
service nginx start

# Create HTML directory and files
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx for custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location / {
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-available/default

# Enable the configuration by creating a symbolic link
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx service to apply changes
service nginx restart

