#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP response header on a brand new Ubuntu machine.

# Function to install and configure Nginx with custom headers
function install_and_configure_nginx() {
    apt-get update
    apt-get install -y nginx

    # Set up index.html and custom_404.html
    echo 'Best School' > /var/www/html/index.html
    echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

    # Set up rewrite rule, custom header, and error page
    re_text="rewrite ^/redirect_me https://www.youtube.com/watch?v=jyknCVczn3Q permanent;"
    h_text="add_header X-Served-By \$hostname;"  # Using $hostname instead of $HOSTNAME
    err_text="error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}"
    sed -i "/listen 80 default_server/a $re_text\n\t$h_text\n\t$err_text" /etc/nginx/sites-available/default

    # Restart Nginx service
    service nginx restart
}

# Execute the function on both web-01 and web-02
install_and_configure_nginx;

