#!/usr/bin/env bash
# Install and configure HAProxy load balancer

# Update packages
sudo apt-get update -y
sudo apt-get upgrade -y

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Backup the original configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Configure HAProxy
lb_config="\
listen 526113-lb-01
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 526113-web-01 34.239.255.194:80 check
    server 526113-web-02 54.164.77.144:80 check
"
sudo sed -i "$ a\\$lb_config" /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart

