#!/usr/bin/env bash
# Displays 4 and then bad luck from China for the 4th loop iteration,
# Displays 9 and then bad luck from Japan for the 9th loop iteration,
# Displays 17 and then bad luck from Italy for the 17th loop iteration.

i=0
while [ $((i++)) -lt 20 ]; do
    case $i in
        4)
            echo "$i and then bad luck from China"
            ;;
        9)
            echo "$i and then bad luck from Japan"
            ;;
        17)
            echo "$i and then bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac
done

