#!/usr/bin/env bash
# Displays hours from 0 to 12 and minutes from 1 to 59.

hour=-1
while [ $((++hour)) -le 12 ]; do
    minute=0
    while [ $((++minute)) -le 59 ]; do
        echo "Hour: $hour, Minute: $minute"
    done
done

